@startuml
skin rose
skinparam componentstyle uml1

package LoMásAbstracto #business {
component Model
}

package LoMenosAbstracto #technology {
component Presentation #technology
component Input #technology
}

package LoIntermedio #implementation {
component Controller #implementation
component ViewAbstractions #implementation
}

package ElFramework #application{
component UnityEngine.dll <<thirdParty>> #lightgray
}

Input --> Controller : 1
Controller --> Model : 2
Presentation --|> ViewAbstractions
Controller -> ViewAbstractions : 3

Presentation -u-> UnityEngine.dll
Input -u-> UnityEngine.dll


Input ..> ViewAbstractions #blue
Input ..> Model #blue
Input .> Presentation #blue

@enduml