@startuml
skin rose
skinparam componentstyle uml1

package LoMásAbstracto #business {
component Model
}

package LoMenosAbstracto #technology {
component Presentation #technology
component Input #technology
}

package LoIntermedio #implementation {
component Controller #implementation
component ViewAbstractions #implementation
}

package ElFramework #application{
component Main #application
}

component UnityEngine.dll <<thirdParty>> #lightgray

Main --> Controller
Main --> Model
Main --> Presentation
Main --> Input
Main --> ViewAbstractions
Input --> Controller : 1
Controller --> Model : 2
Presentation --|> ViewAbstractions
Controller -> ViewAbstractions : 3

Presentation -u-> UnityEngine.dll
Input -u-> UnityEngine.dll


Input ..> ViewAbstractions #blue : guarrería
Input ..> Model #blue : guarrería
Input .> Presentation #blue : guarrería

@enduml