@startuml
skin rose
skinparam componentstyle uml1

package LoMásAbstracto {
component Model
}

package LoMenosAbstracto {
component Presentation
component Input
}

package LoIntermedio {
component Controller
component ViewAbstractions
}

package ElFramework{
component UnityEngine.dll <<thirdParty>> #lightgray
}

Input --> Controller : 1
Controller --> Model : 2
Presentation --|> ViewAbstractions
Controller -> ViewAbstractions : 3

Presentation -u-> UnityEngine.dll
Input -u-> UnityEngine.dll


Input ..> ViewAbstractions #blue : guarrería
Input ..> Model #blue : guarrería
Input .> Presentation #blue : guarrería

@enduml