@startuml
skin rose
left to right direction

control ToggleWeapon
control Shoot
control Reload

boundary WeaponHUD
boundary ToggleWeaponButton
boundary ShootButton
boundary ReloadButton

entity Weapon
entity Magazine
entity Equipment

entity Bullet

ShootButton --> Shoot

Shoot --> Equipment
Shoot --> Bullet
Shoot ..> Weapon
Shoot -u-> WeaponHUD

ToggleWeapon -u-> WeaponHUD
ToggleWeapon --> Equipment
ToggleWeapon ..> Weapon

Reload --> Equipment
Reload -u-> WeaponHUD
ReloadButton --> Reload

Equipment --> Weapon

ToggleWeaponButton --> ToggleWeapon

Weapon --> Magazine

@enduml